version: '3.7'

services:

  db:
    image: postgres:15
    env_file:
      - .env-non-dev
    container_name: UserDbReg
    command: -p 1221
    expose:
      - 1221

    
    
  redis:
    image: redis:7
    container_name: RedisReg
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env-non-dev

  celery:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: Celery_Reg 
    command: bash -c "celery -A tasks.tasks:celery worker --loglevel=info"
    depends_on:
      - redis
  
  flower:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_reg
    command: bash -c "celery -A tasks.tasks:celery flower --loglevel=info"
    ports:
      - 8888:5555
    depends_on:
      - redis
      - celery
    
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_reg_app
    ports:
      - 3000:8000
    depends_on:
      - db
      - redis
      - celery
      - flower
